import os
Import("env")

project_dir = env.subst("$PROJECT_DIR")
html_path   = os.path.join(project_dir, "web", "config.html")
header_path = os.path.join(project_dir, "include", "config_html.h")

with open(html_path, "r", encoding="utf-8") as f:
    html = f.read()

new_content = (
    "// Auto-generated by scripts/embed_html.py — do not edit\n"
    "#pragma once\n\n"
    'static const char CONFIG_HTML[] PROGMEM = R"rawhtml(\n'
    + html
    + '\n)rawhtml";\n'
)

try:
    with open(header_path, "r", encoding="utf-8") as f:
        existing = f.read()
except FileNotFoundError:
    existing = None

if existing != new_content:
    with open(header_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print("Regenerated include/config_html.h from web/config.html")
