import os
import subprocess
from datetime import datetime, timezone
Import("env")

project_dir = env.subst("$PROJECT_DIR")

def git(args):
    try:
        return subprocess.check_output(["git"] + args, cwd=project_dir, stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return None

sha    = git(["rev-parse", "--short", "HEAD"]) or "unknown"
branch = git(["rev-parse", "--abbrev-ref", "HEAD"]) or "unknown"
if branch == "HEAD":
    # Detached HEAD (e.g. CI checkout of a release tag) — show the tag instead
    branch = git(["describe", "--tags", "--exact-match"]) or branch
dirty  = git(["status", "--porcelain"]) != ""  # non-empty means uncommitted changes
build_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
build_info = f"{branch}@{sha}{'*' if dirty else ''} &bull; {build_time}"

files = [
    ("web/config.html", "include/config_html.h", "CONFIG_HTML"),
    ("web/update.html", "include/update_html.h", "UPDATE_HTML"),
]

for html_rel, header_rel, varname in files:
    html_path   = os.path.join(project_dir, html_rel)
    header_path = os.path.join(project_dir, header_rel)

    with open(html_path, "r", encoding="utf-8") as f:
        html = f.read()

    html = html.replace("__BUILD__", build_info)

    new_content = (
        "// Auto-generated by scripts/embed_html.py — do not edit\n"
        "#pragma once\n\n"
        f'static const char {varname}[] PROGMEM = R"rawhtml(\n'
        + html
        + '\n)rawhtml";\n'
    )

    try:
        with open(header_path, "r", encoding="utf-8") as f:
            existing = f.read()
    except FileNotFoundError:
        existing = None

    if existing != new_content:
        with open(header_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"Regenerated {header_rel} from {html_rel}")

build_info_str = f"{branch}@{sha}{'*' if dirty else ''}"

build_info_header = (
    "// Auto-generated by scripts/embed_html.py — do not edit\n"
    "#pragma once\n\n"
    f'static const char BUILD_INFO[] = "{build_info_str}";\n'
    f'static const char BUILD_TIME[] = "{build_time}";\n'
)

build_info_path = os.path.join(project_dir, "include/build_info.h")
try:
    with open(build_info_path, "r", encoding="utf-8") as f:
        existing_build_info = f.read()
except FileNotFoundError:
    existing_build_info = None

if existing_build_info != build_info_header:
    with open(build_info_path, "w", encoding="utf-8") as f:
        f.write(build_info_header)
    print("Regenerated include/build_info.h")
