import os
Import("env")

project_dir = env.subst("$PROJECT_DIR")

files = [
    ("web/config.html", "include/config_html.h", "CONFIG_HTML"),
    ("web/update.html", "include/update_html.h", "UPDATE_HTML"),
]

for html_rel, header_rel, varname in files:
    html_path   = os.path.join(project_dir, html_rel)
    header_path = os.path.join(project_dir, header_rel)

    with open(html_path, "r", encoding="utf-8") as f:
        html = f.read()

    new_content = (
        "// Auto-generated by scripts/embed_html.py — do not edit\n"
        "#pragma once\n\n"
        f'static const char {varname}[] PROGMEM = R"rawhtml(\n'
        + html
        + '\n)rawhtml";\n'
    )

    try:
        with open(header_path, "r", encoding="utf-8") as f:
            existing = f.read()
    except FileNotFoundError:
        existing = None

    if existing != new_content:
        with open(header_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"Regenerated {header_rel} from {html_rel}")
