"""Shared git build-info helpers.

Used by scripts/embed_html.py (PlatformIO pre-build step, generates
include/build_info.h and the __BUILD__ stamp embedded in the web UI) and by
simulator/CMakeLists.txt (generates include/build_info.h for the CMake/WASM
build, which doesn't run PlatformIO pre-build scripts).
"""

import os
import subprocess
import sys
from datetime import datetime, timezone


def _git(args, project_dir):
    try:
        return subprocess.check_output(["git"] + args, cwd=project_dir, stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return None


def get_build_info(project_dir):
    """Returns (build_info, build_time) strings, e.g. ("main@abc1234", "2026-06-10 03:40 UTC")."""
    sha = _git(["rev-parse", "--short", "HEAD"], project_dir) or "unknown"
    branch = _git(["rev-parse", "--abbrev-ref", "HEAD"], project_dir) or "unknown"
    if branch == "HEAD":
        # Detached HEAD (e.g. CI checkout of a release tag) — show the tag instead
        branch = _git(["describe", "--tags", "--exact-match"], project_dir) or branch
    dirty = _git(["status", "--porcelain"], project_dir) != ""
    build_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    build_info = f"{branch}@{sha}{'*' if dirty else ''}"
    return build_info, build_time


def write_build_info_header(project_dir):
    """Writes include/build_info.h if its contents changed. Returns True if rewritten."""
    build_info, build_time = get_build_info(project_dir)
    header = (
        "// Auto-generated by scripts/gen_build_info.py — do not edit\n"
        "#pragma once\n\n"
        f'static const char BUILD_INFO[] = "{build_info}";\n'
        f'static const char BUILD_TIME[] = "{build_time}";\n'
    )
    path = os.path.join(project_dir, "include/build_info.h")
    try:
        with open(path, "r", encoding="utf-8") as f:
            existing = f.read()
    except FileNotFoundError:
        existing = None
    if existing != header:
        with open(path, "w", encoding="utf-8") as f:
            f.write(header)
        return True
    return False


if __name__ == "__main__":
    project_dir = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    if write_build_info_header(project_dir):
        print("Regenerated include/build_info.h")
